### ISSUE TITLE
SqlPackage 2014 arguments mistakes

### ISSUE THREAD

**Issue by VerdonTrigance** [MicrosoftDocs/sql-docs.ru-ru#63]
c:\Program Files (x86)\Microsoft SQL Server\120\DAC\bin&gt;SqlPackage.exe /a:Publish /TargetServerName:dev /TargetDatabaseName:CDB /SourceFile:".\DB.dacpac" /DeployReportPath:".\report.xml" /DiagnosticsFile:".\di.txt"
leads to 
*** Unrecognized command line argument 'DeployReportPath'.
*** Unrecognized command line argument 'DiagnosticsFile'.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: ac30c0d5-990b-1114-cb66-d6bbb789b698
* Version Independent ID: 9432dace-7676-2a86-485a-dd5bc6568e86
* Content: [SqlPackage. exe - SQL Server](https://docs.microsoft.com/ru-ru/sql/tools/sqlpackage?view=sql-server-ver15&viewFallbackFrom=sql-server-2014#feedback)
* Content Source: [docs/tools/sqlpackage.md](https://github.com/MicrosoftDocs/sql-docs.ru-ru/blob/live/docs/tools/sqlpackage.md)
* Product: **sql**
* Technology: **ssdt**
* GitHub Login: @pensivebrian
* Microsoft Alias: **broneill**

**Comment by srvbpigh** [comment]
Hello, @VerdonTrigance
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @VerdonTrigance 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/sql-docs/issues/3443

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
